[project]
name = "uv-install-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nvidia-cublas-cu12==12.4.5.8",
    "nvidia-cusolver-cu12==11.6.1.9",
]
